#!/usr/bin/env node
const bossacli = require('commander');
const cli_orders = require('./cli-orders')
const config = require('./cli-config')

bossacli
  .version('1.0.0', '-v, --version');

bossacli
  .command('countorders')
  .description('Counts the number of sell orders in either the local database (default) or in shopify (see option)')
  .option('-r, --remote', 'Count orders directly in shopify')
  .option('-d, --debug', 'Logs information about execution')
  .action(cli_orders.countLocal)

bossacli
  .command('*')
  .action( () => bossacli.help())

bossacli.parse(process.argv);
if (!process.argv.slice(2).length) {
  bossacli.help();
} 